'use strict';
window.PLAY_UI_EN = {
  'Profile & Slots':'Profiles & Slots',
  'Community-Profile · UV Try':'Community profiles · UV Try',
  'Diagnostics & Hilfe':'Diagnostics & Help',
  'Mit einem vorausgewählten Profil anfangen. Eigene Einstellungen für später speichern.':'Start with a preselected profile. Save your own settings for later.',
  'Dein GPU-Modell ist vorausgewählt. Profile aussuchen, testen und bewerten, ohne eine eigene Kurve zu bauen.':'Your GPU model is preselected. Choose, test and rate profiles without building your own curve.',
  'Das passende Profil automatisch verwenden, sobald Play dein Spiel erkennt.':'Automatically use the right profile when Play detects your game.',
  'Spiele und Profile zuordnen. Für jedes Spiel die passende Einstellung finden.':'Assign profiles to games. Find the right settings for each title.',
  'Den GPU-Takt an die tatsächliche Last im Spiel anpassen und unnötigen Verbrauch reduzieren.':'Adapt GPU clocks to the actual game load and reduce unnecessary power consumption.',
  'Nach erkannten Treiberabstürzen automatisch nachjustieren. Für Spielprofile und globale Profile.':'Automatically adjust after detected driver crashes. For game profiles and global profiles.',
  'Auf dem Desktop eine niedrigere Bildwiederholrate, beim Spielen wieder die native Rate.':'Use a lower desktop refresh rate and the native rate while gaming.',
  'Spannung und Takt gezielt abstimmen. Den eigenen Weg zwischen Leistung und Verbrauch finden.':'Fine-tune voltage and clock. Find your balance between performance and power draw.',
  'Spannungspunkte und Takt unter Testlast prüfen. Ergebnisse für die eigene Optimierung nutzen.':'Check voltage points and clocks under test load. Use the results to refine your settings.',
  'Einen Ausgangspunkt aus der Werkskurve deiner GPU ermitteln und als Profil übernehmen.':'Derive a starting point from your GPU’s factory curve and save it as a profile.',
  'GPU-Automatik, feste Drehzahl oder eigene Lüfterkurve: Kühlung und Lautstärke abstimmen.':'GPU automatic control, fixed speed or your own fan curve: balance cooling and noise.',
  'Zusätzliche experimentelle Takt- und Spannungsparameter für erfahrene Nutzer.':'Additional experimental clock and voltage parameters for experienced users.',
  'Bildrate, Verbrauch und Temperaturen im Blick behalten. Veränderungen beim Spielen sehen.':'Keep an eye on frame rate, power draw and temperatures. See changes while gaming.',
  'Die gewünschte GPU wählen und allgemeine Einstellungen zentral finden.':'Choose your GPU and find general settings in one place.',
  'Neue Play-Versionen prüfen, herunterladen und nach Bestätigung installieren.':'Check for new Play versions, download them and install after confirmation.',
  'Ein Problem nachvollziehbar beschreiben und passende Diagnosedaten zusammenstellen.':'Describe an issue clearly and collect useful diagnostic information.',
  'Einstieg':'Getting started',
  'Automatik & Effizienz':'Automation & Efficiency',
  'Feintuning':'Fine-tuning',
  'Übersicht & Hilfe':'Monitoring & Help',
  'Mit Profilen anfangen, Erfahrungen aus der Community nutzen und Spiele zuordnen.':'Start with profiles, learn from the community and assign games.',
  'Weniger manuell nachregeln: Takt, Stabilität und Bildwiederholrate passend zum Einsatz.':'Less manual adjustment: clocks, stability and refresh rate suited to what you are doing.',
  'Eigene Kurven und Tests oder ein Ausgangspunkt mit Auto-UV. Dazu Lüfter und Expertenoptionen.':'Custom curves and tests, or a starting point with Auto-UV. Plus fan control and expert options.',
  'Messwerte sehen, Play einrichten, aktuell halten und bei Problemen weiterkommen.':'View readings, set up Play, keep it updated and get help with issues.',
  'Originales NV-UV Play Hauptfenster mit Profilplätzen und Funktionsschaltern':'Original NV-UV Play main window with profile slots and feature switches',
  'Originalaufnahme · Play v2.0.3. Sichtbare Profile und Werte gehören zur Aufnahme.':'Original capture · Play v2.0.3. Profiles and values shown belong to the capture.',
  'Originaler Play Kurveneditor mit Spannungskurve, Profilplätzen und Bearbeitungsoptionen':'Original Play curve editor with voltage curve, profile slots and editing options',
  'Originalaufnahme · Play v2.0.3. Die gezeigte Kurve dient hier nur zur Erklärung der Bedienung.':'Original capture · Play v2.0.3. The curve shown only illustrates how to use the controls.',
  'Originale DCC Einstellungen mit Automatic, NVIDIA Power Efficiency Mode, Framelimit und Lernständen':'Original DCC settings with Automatic, NVIDIA Power Efficiency Mode, frame cap and learning data',
  'Originalaufnahme · DCC-Einstellungen aus dem lokalen Play-v2.0.9-Teststand.':'Original capture · DCC settings from a Play v2.0.9 test build.',
  'Originale Stabilizer Einstellungen mit Strategie, Takt- und Spannungsschritten sowie Grenzen':'Original Stabilizer settings with strategy, clock and voltage steps, and limits',
  'Originalaufnahme · Stabilizer aus dem lokalen Play-v2.0.9-Teststand. Die angezeigten Werte sind keine Empfehlung für deine GPU.':'Original capture · Stabilizer from a Play v2.0.9 test build. These values are not recommendations for your GPU.',
  'Originales Play Overlay-Fenster mit Anzeigeoptionen und Live-Vorschau':'Original Play overlay window with display options and live preview',
  'Originalaufnahme · Overlay aus dem lokalen Play-v2.0.9-Teststand. Die Aufnahme enthält simulierte Sensorwerte des UI-Tests.':'Original capture · Overlay from a Play v2.0.9 test build. The capture contains simulated sensor readings used for UI testing.',
  'Originale Play Settings mit GPU-Auswahl und den verfügbaren Einstellungsbereichen':'Original Play Settings with GPU selection and available settings sections',
  'Originalaufnahme · Settings aus dem lokalen Play-v2.0.9-Teststand ohne aktive GPU.':'Original capture · Settings from a Play v2.0.9 test build with no active GPU.',
  'Eigener Profilplatz 5':'Custom profile slot 5',
  'Eigener Profilplatz 6':'Custom profile slot 6',
  'Profilplätze':'Profile slots',
  'Spannungs-Frequenz-Kurve':'Voltage-frequency curve',
  'Overlay aktivieren':'Enable overlay',
  'Fenster & alle Erklärungen öffnen ↗':'Open window & all explanations ↗',
  'Mehr zu dieser Funktion ↗':'More about this feature ↗',
  'Im Originalfenster':'In the original window',
  'Im Hauptfenster':'In the main window',
  'Im Kurveneditor':'In the curve editor',
  'In den Einstellungen':'In Settings',
  'Optionen anklicken':'click an option',
  'Klickbereiche ausblenden':'Hide click areas',
  'Klickbereiche zeigen':'Show click areas',
  'Fenster seitlich wischen oder mit den Pfeiltasten bewegen →':'Swipe the window sideways or use the arrow keys →',
  'Originalfenster, auf kleinen Bildschirmen horizontal scrollbar':'Original window, horizontally scrollable on small screens',
  'Die Aufnahme zeigt den Zugang zu':'This capture shows how to access',
  'Die Optionen der Funktion findest du unten erklärt.':'Its options are explained below.',
  'Fan curve in Play öffnen':'Open Fan curve in Play',
  'In neueren Play-Versionen findest du die Lüftersteuerung direkt im Hauptfenster. Für diesen Dialog liegt in der Vorschau noch keine passende Originalaufnahme vor. Die verfügbaren Optionen sind unten erklärt.':'In newer Play versions, fan control is available directly in the main window. This preview does not yet have a matching original capture of that dialog. The available options are explained below.',
  'Was bringt dir das?':'How does it help?',
  'So nutzt du es in Play':'How to use it in Play',
  'Passende Funktionen':'Related features',
  'Die Optionen, einzeln erklärt.':'Each option explained.',
  'Play-Funktion erklären':'Explain a Play feature',
  'Öffnet eine Funktion mit Originalaufnahme und Erklärungen in dieser Webseite. Keine Hardwarewirkung.':'Opens a feature with an original capture and explanations on this website. No hardware changes.',
  'Unbekannte Play-Funktion.':'Unknown Play feature.',
  'Option im Play-Originalfenster erklären':'Explain an option in the original Play window',
  'Öffnet die anklickbare Erklärung einer sichtbaren Option im Originalfenster. Zuerst eine Funktion mit open_play_guide öffnen. Keine Hardwarewirkung.':'Opens the explanation for a visible option in the original window. First open a feature with open_play_guide. No hardware changes.',
  'Exakte sichtbare Beschriftung der Option, z. B. Correction strategy oder NVIDIA Max Frame Rate.':'Exact visible option label, such as Correction strategy or NVIDIA Max Frame Rate.',
  'Eine gültige Beschriftung ist erforderlich.':'A valid label is required.',
  'Diese Option ist im aktuellen Fenster nicht vorhanden.':'This option is not present in the current window.'
};
